name: publish-fw-nuget

on:
  push:
    branches:
      - 'dev/**'

jobs:
  build:

    runs-on: windows-latest
    
    - name: Get dotnet
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'
      
    - name: Install Python3   
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        architecture: 'x64'
		
	- uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
        
    - name: Build & Pack Nugets
      run: python build.py
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} 
